name: example
description: A new Flutter project.

# change version to be the same of backend version for android
version: 3.0.0

environment:
  sdk: ">=2.18.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  driver_package:
    path: ../

# if you get package from GitHub
#  driver_package:
#    git:
#      url: "https://github.com/Excellent-Protection/Driver-Package.git"
#      ref: "pre_production"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

  # Run This To Enable Splash Screen=> flutter pub run flutter_native_splash:create
  flutter_native_splash: ^2.2.10+1
flutter_native_splash:
  color: "#ffffff"
  image: "assets/images/default_splash.png"
  android: true
  ios: true
  android_gravity: fill
  ios_content_mode: scaleAspectFill

  # Run This To set icon For the App => flutter pub run flutter_launcher_icons:main
  flutter_launcher_icons: ^0.10.0
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"

flutter:

  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: DinNextLight
      fonts:
        - asset: assets/fonts/DinNextMedium.ttf
          weight: 900
        - asset: assets/fonts/DinNextLight.ttf
          weight: 900
        - asset: assets/fonts/DinNextBold.ttf
          weight: 900
    - family: Almarai
      fonts:
        - asset: assets/fonts/Almarai-Regular.ttf
          weight: 500

    - family: hanimation
      fonts:
        - asset: assets/fonts/hanimation-Regular.ttf
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Medium.ttf

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
