name: driver_package
description: Driver Package
version: 0.0.1
homepage: https://github.com/Excellent-Protection/Driver-Package

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.3.2"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^0.13.5
  get: ^4.3.8
  flutter_svg: ^1.1.5
  intl: ^0.17.0
  shared_preferences: ^2.0.5
  google_maps_flutter: ^2.0.6
  geolocator: ^9.0.1
  geocoding: ^2.0.4
  url_launcher: ^6.0.3
  image_picker: ^0.8.0+3
  flutter_bloc: ^8.1.1
  loading_indicator: ^3.1.0
  equatable:
  flutter_screenutil: ^5.0.0+2
  auto_size_text: ^3.0.0
  signature: ^5.0.0
  package_info: ^2.0.2
  internet_connection_checker: ^0.0.1+4
  flutter_neat_and_clean_calendar: ^0.3.8+22
  onesignal_flutter: ^3.4.1




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  dependency_validator: ^3.2.2

flutter:
